### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by YerDatsRight** [bloofirephoenix/BrokenNameTags#1]
My friends pet died and it crashed the server so we tested to see if it was the named pet dying that caused it so my friend spawned a wolf, named it and killed it and it indeed crashed the server I have no idea what's causing it but here's the crash file
[message (1).txt](https://github.com/bloofirephoenix/BrokenNameTags/files/6336836/message.1.txt)

**Comment by dashiellwascool** [comment]
I've submitted the patch to CurseForge and will be closing the issue once it goes through.
