### ISSUE TITLE
1.19 update

### ISSUE THREAD

**Issue by V-lpen** [bloofirephoenix/BrokenNameTags#4]
Love this mod, and id love to be able to update my server to 1.19!

**Comment by dashiellwascool** [comment]
I didn't realize people still use this thing. Updating right now, almost done. Just gotta run some final tests then I will upload to Curseforge and Modrinth. After those uploads succeed I will close this issue.

**Comment by V-lpen** [comment]
thanks so much! This is one of my favorite mods for a RP server.

**Comment by dashiellwascool** [comment]
Update is uploaded and approved
